config/routes.rb
Rails.application.routes.draw do

   root 'employees#index'
   resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :firstname,presence:{message: "this field is required"}
validates :lastname,presence:{message: "this field is required"}
validates :city,presence:{message: "this field is required"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
	end

	def new
		@employee=Employee.new

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_detail_helper.rb
module EmployeeDetailHelper
end

app/views/employees/index.html.erb
<html>
<head>
<h1>hello employees</h1></head>
<body>
<%=link_to"click",new_employee_path%>
</body>
</html>

app/views/employees/new.html.erb
 <html>
<head>
<h1>employee database</h1>
<!-- </head>
<body>
firstname<input type='text' name="first name">
lastname<input type='text' name="last name">
city<input type='text' name="city">
<input type='button' name="submit" value='submit'> 
</body>
</html>
  -->









 <%=form_for @employee do|f|%>

 <div class="form-group">
 <%=f.label :firstname%>
 <%=f.text_field :firstname%>
 </div>


 <div class="form-group">
 <%=f.label :lastname%>
 <%=f.text_field :lastname%>
 </div>
  
<div class="form-group">
 <%=f.label :city%>
 <%=f.text_field :city%>
 </div>

 
 <%=f.submit "submit"%>
 <%end%>
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Employee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>